# The URL the site will be built for
base_url = "https://robinhundt.github.io/blog/"

title = "Robin Hundt"
# a description; you can use markdown here if you like
description="Computer Science student interested in Rust, bouldering, hiking and lots of other stuff."

theme = "Ergo"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[extra]
# theme options, (Submit an issue if any social network you may want is missing here: https://github.com/InsidiousMind/Ergo/issues)
profile = "profile.jpg" # the name of the profile picture in static/img/
website = "robinhundt.github.io/blog/"
github = "robinhundt"
# twitter = "insipx"
# linkedin = ""
email = "robin.hundt@posteo.de"
# instagram = ""
# keybase = ""
# reddit = ""
# youtube = ""
